import 'boxicons/css/boxicons.min.css';
import Image from 'next/image';
import "./globals.css";
import Resbtn from '@/components/rpbtn';
import HamburgerMenu from '@/components/humburge';
import Link from 'next/link';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <nav className="h-[20vh] w[100vw] ">
          {/*------------------- FIRST NAV ----------------*/}
          <div className="h-[30%] w[100%] bg-[#7e33e0] flex justify-around">

            <div className='flex gap-2  items-center'>
              <i className='bx bxl-gmail nav1text max-800:text-[10px]'></i>
              <p className='nav1text max-800:text-[10px]'>ammar@gamil.com</p>
              <i className='bx bxs-phone-call nav1text max-800:text-[5px]' ></i>
              <p className='nav1text max-800:text-[10px]'>+92 2398494</p>
            </div>
            <div className='flex gap-2 max-800:gap-1 items-center'>
              <p className='nav1text max-800:text-[6px]'>Enlish </p>
              <i className='bx bx-chevron-down nav1text max-800:text-[10px]'></i>
              <p className='nav1text max-800:text-[6px]'> USD</p>
              <i className='bx bx-chevron-up nav1text max-800:text-[10px]'></i>
              <p className='nav1text max-800:text-[6px]'>Login</p>
              <i className='bx bx-user nav1text max-800:text-[10px]'></i>
              <p className='nav1text max-800:text-[6px]'>Whishlist</p>
              <i className='bx bx-heart nav1text max-800:text-[10px]'></i>
              <i className='bx bx-cart nav1text max-800:text-[10px]'></i>
            </div>
            {/*------------------- FIRST NAV ----------------*/}

            {/*------------------- SECOND NAV ----------------*/}
          </div>
          <div className='w-[100%] h-[70%] bg-white flex justify-around items-center '>
            <div>
              <p className='text-[30px] font-bold'>HEKTO</p>
            </div>
            <div className='max-800:hidden'>
              <ul className='flex'>
                <li className='p-3'><Link href={"/"}>Home  </Link> </li>
                < li className='p-3 font-sans'><Link href={"/Login"}>Login </Link></li>
                <li className='p-3 font-sans'><Link href={"Products"}>All Products </Link></li>
                <li className='p-3 font-sans'><Link href={"Blog"}>Blog </Link></li>
                <li className='p-3 font-sans'><Link href={"About"}>About </Link></li>
                <li className='p-3 font-sans'><Link href={"Contact"}>Contact </Link></li>
              </ul>
            </div>
            <div>
              <input type="text" className='w-[23vw] rounded-full p-1 flex items-center justify-center border-2 border-black' placeholder='SEARCH ' />
            </div>
        
{/*------------------- HUMBURG NAV ----------------*/}



<div>
      <HamburgerMenu />
      
    </div>




          </div>
          {/*------------------- SECOND NAV ----------------*/}

        </nav>


        {children}
        {/*------------------- FOOTER IMG----------------*/}
        <div>
          <Image
            src={"/Assets/pic29.png"}
            alt="pic"
            width={1400}
            height={100}
            className=" inset-0 w-full h-full object-cover mb-3"/>
        </div>

        <footer className='w-[100%]  bg-[#eeeffb] flex flex-wrap gap-3 p-3'>
          {/*------------------- 1 DIV----------------*/}
          <div className="h-[100%] w-[300px] ">
            <div>
              <p className='text-[30px] font-bold mb-4'>HEKTO</p>
            </div>
            <div>
              <div className='flex mb-7'>
                <input type="text" className='w-15 bg-gray-200 text-black '
                  placeholder='Enter Your Email' />
                <span><Resbtn name={"Sign Up"} /></span>
              </div>
              <ul className='leading-7'>
                <li>Contact Info</li>
                <li>17 Princess Road, London, Greater London NW1 8JR, UK</li>
              </ul>

            </div>
          </div>
          {/*------------------- 2 DIV----------------*/}
          <div className="h-[100%] w-[300px]  ">
            <h3 className='text-black font-bold mb-5  text-[20px]'>Catagories</h3>
            <ul className='leading-7'>
              <li>Laptops & Computers</li>
              <li>Cameras & Photography</li>
              <li>Smart Phones & Tablets</li>
              <li>Video Games & Consoles</li>
              <li>Waterproof Headphones</li>
            </ul>
          </div>
          {/*------------------- 3 DIV----------------*/}
          <div className="h-[100%] w-[300px] ">
            <h3 className='text-black font-bold mb-5 text-[20px]'>Customer Care</h3>
            <ul className='leading-7'>
              <li>My Account</li>
              <li>Discount</li>
              <li>Returns</li>
              <li>Orders History</li>
              <li>Order Tracking</li>

            </ul>
          </div>
          {/*------------------- 4 DIV----------------*/}
          <div className="h-[100%] w-[300px]">
            <h3 className='text-black font-bold mb-5 text-[20px]'>Pages</h3>
            <ul className='leading-7'>
              <li>Blog</li>
              <li>Browse the Shop</li>
              <li>Pre-Built Pages</li>
              <li>Visual Composer Elements</li>
              <li>WooCommerce Pages</li>

            </ul>
          </div>
        </footer>
      </body>
    </html>
  )
}
